// AIO Graphics Test - Dear ImGui single-window shell.
//
// Phase 0 (de-risk) proved the C++ / Dear ImGui / Direct3D 11 path builds green in
// CI and launches under the FEX / arm64ec Proton container (no c000001d). Phase 1
// builds the real shell chrome, a 1:1 reproduction of the approved HTML mockup
// (aio-redesign.html): a top app bar with identity + List/Grid segmented control +
// theme toggle, a right-docked grouped test menu (List and Grid treatments), a left
// dark "instrument" viewport with a live-frametiming HUD (API chip + FPS + sparkline)
// and a bottom telemetry strip, and a footer. It is still additive and reachable
// ONLY via the --imgui flag; the classic menu.c/cube_* shell is untouched. No live
// per-test rendering yet (Phase 2) - the viewport is a themed placeholder and the
// menu updates HUD/telemetry/crumb labels from a static catalog.
//
// Renderer notes (repo lesson): d3d11.dll and dxgi are resolved DYNAMICALLY so the
// exe still LAUNCHES on a container without DXVK (it just reports D3D11 missing). We
// never import D3D11CreateDeviceAndSwapChain at link time. Dear ImGui's DX11 backend
// needs D3DCompile(); a lazy-loading forwarding shim (below) keeps d3dcompiler
// dynamic too, so d3d11 / dxgi / d3dcompiler are ALL dynamic.
//
// Fonts are compiled in (no external files): Cascadia Mono (mono role - data / HUD /
// labels) and Inter (UI role - title / row names), embedded as base85-compressed TTF
// via ImGui's binary_to_compressed_c.

#include <windows.h>
#include <d3d11.h>
#include <dxgi.h>
#include <d3dcompiler.h>
#include <cstdint>
#include <cstdio>
#include <cfloat>

#include "imgui.h"
#include "backends/imgui_impl_win32.h"
#include "backends/imgui_impl_dx11.h"

#include "shell_imgui.h"
#include "menu.h"  // AIO_VERSION

// Embedded fonts (generated by imgui/misc/fonts/binary_to_compressed_c -base85).
#include "font_mono.inc"  // CascadiaMono_compressed_data_base85
#include "font_ui.inc"    // InterUI_compressed_data_base85

// ---------------------------------------------------------------------------
// D3DCompile forwarding shim (keeps d3dcompiler dynamic - see header comment).
// ---------------------------------------------------------------------------
extern "C" HRESULT WINAPI D3DCompile(LPCVOID pSrcData, SIZE_T SrcDataSize, LPCSTR pSourceName,
                                     const D3D_SHADER_MACRO *pDefines, ID3DInclude *pInclude,
                                     LPCSTR pEntrypoint, LPCSTR pTarget, UINT Flags1, UINT Flags2,
                                     ID3DBlob **ppCode, ID3DBlob **ppErrorMsgs) {
    static pD3DCompile s_fn = nullptr;
    static bool s_tried = false;
    if (!s_tried) {
        s_tried = true;
        const char *dlls[] = {"d3dcompiler_47.dll", "d3dcompiler_46.dll", "d3dcompiler_43.dll"};
        for (int i = 0; i < 3 && !s_fn; ++i) {
            HMODULE h = LoadLibraryA(dlls[i]);
            if (h) s_fn = (pD3DCompile)GetProcAddress(h, "D3DCompile");
        }
    }
    if (!s_fn) {
        if (ppCode) *ppCode = nullptr;
        if (ppErrorMsgs) *ppErrorMsgs = nullptr;
        return E_NOTIMPL;
    }
    return s_fn(pSrcData, SrcDataSize, pSourceName, pDefines, pInclude, pEntrypoint, pTarget, Flags1,
                Flags2, ppCode, ppErrorMsgs);
}

extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam,
                                                             LPARAM lParam);

// ---------------------------------------------------------------------------
// Direct3D 11 device / swapchain (created via dynamic d3d11.dll load).
// ---------------------------------------------------------------------------
typedef HRESULT(WINAPI *PFN_D3D11CreateDeviceAndSwapChain_t)(
    IDXGIAdapter *, D3D_DRIVER_TYPE, HMODULE, UINT, const D3D_FEATURE_LEVEL *, UINT, UINT,
    const DXGI_SWAP_CHAIN_DESC *, IDXGISwapChain **, ID3D11Device **, D3D_FEATURE_LEVEL *,
    ID3D11DeviceContext **);

static ID3D11Device *g_dev = nullptr;
static ID3D11DeviceContext *g_ctx = nullptr;
static IDXGISwapChain *g_swap = nullptr;
static ID3D11RenderTargetView *g_rtv = nullptr;

static void create_rtv() {
    ID3D11Texture2D *back = nullptr;
    g_swap->GetBuffer(0, IID_ID3D11Texture2D, (void **)&back);
    if (back) {
        g_dev->CreateRenderTargetView(back, nullptr, &g_rtv);
        back->Release();
    }
}

static void release_rtv() {
    if (g_rtv) {
        g_rtv->Release();
        g_rtv = nullptr;
    }
}

static bool create_device(HWND hwnd) {
    HMODULE d3d11 = LoadLibraryA("d3d11.dll");
    PFN_D3D11CreateDeviceAndSwapChain_t create =
        d3d11 ? (PFN_D3D11CreateDeviceAndSwapChain_t)GetProcAddress(d3d11,
                                                                    "D3D11CreateDeviceAndSwapChain")
              : nullptr;
    if (!create) return false;

    DXGI_SWAP_CHAIN_DESC scd;
    ZeroMemory(&scd, sizeof(scd));
    scd.BufferCount = 2;
    scd.BufferDesc.Width = 0;
    scd.BufferDesc.Height = 0;
    scd.BufferDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    scd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    scd.OutputWindow = hwnd;
    scd.SampleDesc.Count = 1;
    scd.Windowed = TRUE;
    scd.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;

    const D3D_FEATURE_LEVEL want[] = {D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_1,
                                      D3D_FEATURE_LEVEL_10_0};
    D3D_FEATURE_LEVEL got;
    HRESULT hr = create(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0, want,
                        (UINT)(sizeof(want) / sizeof(want[0])), D3D11_SDK_VERSION, &scd, &g_swap,
                        &g_dev, &got, &g_ctx);
    if (FAILED(hr)) return false;
    create_rtv();
    return true;
}

static void destroy_device() {
    release_rtv();
    if (g_swap) { g_swap->Release(); g_swap = nullptr; }
    if (g_ctx) { g_ctx->Release(); g_ctx = nullptr; }
    if (g_dev) { g_dev->Release(); g_dev = nullptr; }
}

static LRESULT WINAPI wnd_proc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp) {
    if (ImGui_ImplWin32_WndProcHandler(hwnd, msg, wp, lp)) return 1;
    switch (msg) {
        case WM_SIZE:
            if (g_dev && wp != SIZE_MINIMIZED) {
                release_rtv();
                g_swap->ResizeBuffers(0, (UINT)LOWORD(lp), (UINT)HIWORD(lp), DXGI_FORMAT_UNKNOWN, 0);
                create_rtv();
            }
            return 0;
        case WM_KEYDOWN:
            if (wp == VK_ESCAPE) { PostMessage(hwnd, WM_CLOSE, 0, 0); return 0; }
            break;
        case WM_DESTROY:
            PostQuitMessage(0);
            return 0;
    }
    return DefWindowProc(hwnd, msg, wp, lp);
}

// ===========================================================================
// Palette (1:1 with the mockup's CSS custom properties).
// ===========================================================================
static inline ImU32 H(unsigned rgb, int a = 255) {
    return IM_COL32((rgb >> 16) & 0xff, (rgb >> 8) & 0xff, rgb & 0xff, a);
}
static inline ImVec4 V(unsigned rgb, float a = 1.0f) {
    return ImVec4(((rgb >> 16) & 0xff) / 255.0f, ((rgb >> 8) & 0xff) / 255.0f,
                  (rgb & 0xff) / 255.0f, a);
}

struct Palette {
    ImU32 bg, bg2, panel, panel2, panelhi, line, line2, text, muted, faint, accent, accentInk;
    ImU32 scr, scr2, scrLine, scrText, scrMuted;  // dark "screen" region (theme-independent)
    ImU32 good, warn, bad;
};
static Palette PAL;
static bool g_dark = true;

// Per-API chip hues (theme-independent). H_TOOL resolves to the theme accent.
enum { H_VK, H_GL, H_DX12, H_DX11, H_DX10, H_DX9, H_DX8, H_DDRAW, H_DEMO, H_TOOL, H_COUNT };
static ImU32 g_hue[H_COUNT];
static void init_hues() {
    g_hue[H_VK] = H(0xe5484d);   g_hue[H_GL] = H(0x5b8def);   g_hue[H_DX12] = H(0x41bf6d);
    g_hue[H_DX11] = H(0x22c1ad); g_hue[H_DX10] = H(0x3fb9a0);  g_hue[H_DX9] = H(0xe0a13a);
    g_hue[H_DX8] = H(0x94a1b0);  g_hue[H_DDRAW] = H(0x94a1b0); g_hue[H_DEMO] = H(0xa678f0);
    g_hue[H_TOOL] = H(0x2fd6c3);  // overwritten by theme accent at draw time
}
static inline ImU32 hue_col(int h) { return h == H_TOOL ? PAL.accent : g_hue[h]; }

// Fonts.
static ImFont *g_ui = nullptr;       // Inter 14 - row names
static ImFont *g_ui_big = nullptr;   // Inter 19 - title
static ImFont *g_mono = nullptr;     // Cascadia 12 - data / values / fps hints
static ImFont *g_mono_sm = nullptr;  // Cascadia 10 - group headers / telemetry keys
static ImFont *g_mono_bg = nullptr;  // Cascadia 20 - HUD FPS

static void apply_theme(bool dark) {
    g_dark = dark;
    // Screen region colors are the same dark instrument surface in BOTH themes.
    PAL.scr = H(0x080c11); PAL.scr2 = H(0x0c1219); PAL.scrLine = H(0x1b2530);
    PAL.scrText = H(0xdce6ef); PAL.scrMuted = H(0x7d8b9b);
    PAL.good = H(0x2fae5f); PAL.warn = H(0xd99626); PAL.bad = H(0xe5484d);
    if (dark) {
        PAL.bg = H(0x070a0e); PAL.bg2 = H(0x0a0e13); PAL.panel = H(0x0f151c);
        PAL.panel2 = H(0x131b24); PAL.panelhi = H(0x18222d); PAL.line = H(0x212c38);
        PAL.line2 = H(0x2c3b4b); PAL.text = H(0xe3ebf3); PAL.muted = H(0x8a97a6);
        PAL.faint = H(0x5f6c7c); PAL.accent = H(0x2fd6c3); PAL.accentInk = H(0x7ff0e4);
    } else {
        PAL.bg = H(0xe9edf1); PAL.bg2 = H(0xdfe4ea); PAL.panel = H(0xffffff);
        PAL.panel2 = H(0xf2f5f8); PAL.panelhi = H(0xe8edf2); PAL.line = H(0xd6dce3);
        PAL.line2 = H(0xc3ccd6); PAL.text = H(0x141b23); PAL.muted = H(0x5b6775);
        PAL.faint = H(0x8592a0); PAL.accent = H(0x0f9e8f); PAL.accentInk = H(0x0b7a6e);
    }

    ImGuiStyle &s = ImGui::GetStyle();
    if (dark) ImGui::StyleColorsDark(); else ImGui::StyleColorsLight();
    s.WindowRounding = 0.0f; s.ChildRounding = 10.0f; s.FrameRounding = 7.0f;
    s.GrabRounding = 6.0f; s.ScrollbarRounding = 6.0f; s.PopupRounding = 8.0f;
    s.WindowBorderSize = 0.0f; s.ChildBorderSize = 0.0f; s.FrameBorderSize = 0.0f;
    s.ScrollbarSize = 10.0f;
    s.Colors[ImGuiCol_WindowBg] = V(dark ? 0x0f151c : 0xffffff);
    s.Colors[ImGuiCol_ChildBg] = ImVec4(0, 0, 0, 0);
    s.Colors[ImGuiCol_Text] = V(dark ? 0xe3ebf3 : 0x141b23);
    s.Colors[ImGuiCol_TextDisabled] = V(dark ? 0x5f6c7c : 0x8592a0);
    s.Colors[ImGuiCol_Border] = V(dark ? 0x212c38 : 0xd6dce3);
    s.Colors[ImGuiCol_ScrollbarBg] = ImVec4(0, 0, 0, 0);
    s.Colors[ImGuiCol_ScrollbarGrab] = V(dark ? 0x2c3b4b : 0xc3ccd6);
    s.Colors[ImGuiCol_ScrollbarGrabHovered] = V(dark ? 0x5f6c7c : 0x8592a0);
    s.Colors[ImGuiCol_ScrollbarGrabActive] = V(dark ? 0x2fd6c3 : 0x0f9e8f);
    s.Colors[ImGuiCol_FrameBg] = ImVec4(0, 0, 0, 0);
}

// ===========================================================================
// Test catalog - sourced from the real code (menu.c g_items + cube.c routing;
// cube_d3d11.c kScenes[] split the way menu.c's show_dx11_scenes / _demos /
// _scaling group them). fps values are representative device numbers (mockup
// style). Tools carry no fps and hide the HUD/telemetry.
// ===========================================================================
struct Test {
    const char *name;     // menu row / grid tile name
    const char *api;      // HUD API label
    const char *path;     // telemetry "Translation path" (nullptr for tools)
    const char *present;  // telemetry "Present" (nullptr -> default FIFO)
    int hue;
    int fps;              // 0 = no fps hint (tools)
    bool tool;            // hide HUD + telemetry, show tool placeholder
};
struct Group { const char *name; const Test *items; int n; };

static const Test kBackends[] = {
    {"Vulkan", "Vulkan", "vulkan-1 -> Turnip", "FIFO (vsync off)", H_VK, 1420, false},
    {"OpenGL", "OpenGL", "opengl32 -> Zink -> Vulkan", "wglSwapInterval 0", H_GL, 519, false},
    {"Direct3D 12", "Direct3D 12", "d3d12 -> VKD3D -> Turnip", "Flip discard", H_DX12, 850, false},
    {"Direct3D 11", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3192, false},
    {"Direct3D 10", "Direct3D 10", "d3d10 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX10, 2604, false},
    {"Direct3D 9", "Direct3D 9", "d3d9 -> DXVK -> Turnip", "Immediate", H_DX9, 1175, false},
    {"Direct3D 8", "Direct3D 8", "d3d8 -> d3d9 -> DXVK", "Immediate", H_DX8, 603, false},
    {"DirectDraw (DX7)", "DirectDraw", "ddraw -> DXVK -> Turnip", "Blt flip", H_DDRAW, 884, false},
};
static const Test kScenes[] = {
    {"Spin", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3192, false},
    {"Textured", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3110, false},
    {"Instanced 512x", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3114, false},
    {"Tessellation", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3185, false},
    {"Compute Particles", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 2303, false},
    {"GS Exploder", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 2870, false},
    {"Atomics", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 2540, false},
    {"Dolphin", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3032, false},
    {"Banding Test", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3180, false},
    {"Draw Stress 128", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 2410, false},
    {"Draw Stress 256", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 1780, false},
    {"Draw Stress 512", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 1140, false},
    {"Draw Stress 1024", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 632, false},
    {"Draw Stress 2048", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 331, false},
};
static const Test kDemos[] = {
    {"Free Look", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 80, false},
    {"Planet Fly", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 76, false},
    {"Raymarch SDF", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 88, false},
    {"Ocean", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 74, false},
    {"Ocean v2", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 68, false},
    {"Mandelbulb", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 52, false},
    {"Nebula", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 90, false},
    {"Nebula HD", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 61, false},
    {"Showcase", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 70, false},
    {"Space", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 120, false},
    {"Desert", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 82, false},
    {"Cityscape", "Direct3D 11", "raymarch  d3d11 -> DXVK", "FIFO", H_DEMO, 66, false},
    {"Cel Shading", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO", H_DEMO, 240, false},
    {"Matcap", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO", H_DEMO, 256, false},
};
static const Test kScaling[] = {
    {"Combo Card", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3190, false},
    {"Zone Plate", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3200, false},
    {"Resolution Wedge", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3195, false},
    {"Lines & Diagonals", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3188, false},
    {"Checkerboard", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3192, false},
    {"Hard Edges", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3186, false},
    {"Banding Test", "Direct3D 11", "d3d11 -> DXVK -> Turnip", "FIFO (vsync off)", H_DX11, 3180, false},
};
static const Test kTools[] = {
    {"GPU Info", "GPU Info", nullptr, nullptr, H_TOOL, 0, true},
    {"Benchmark", "Benchmark", nullptr, nullptr, H_TOOL, 0, true},
    {"Disk Speed", "Disk Speed", nullptr, nullptr, H_TOOL, 0, true},
};
static const Group kGroups[] = {
    {"Graphics Backends", kBackends, (int)(sizeof(kBackends) / sizeof(kBackends[0]))},
    {"DX11 Scenes", kScenes, (int)(sizeof(kScenes) / sizeof(kScenes[0]))},
    {"Showcase Demos", kDemos, (int)(sizeof(kDemos) / sizeof(kDemos[0]))},
    {"Scaling Tests", kScaling, (int)(sizeof(kScaling) / sizeof(kScaling[0]))},
    {"Tools", kTools, (int)(sizeof(kTools) / sizeof(kTools[0]))},
};
static const int kGroupCount = (int)(sizeof(kGroups) / sizeof(kGroups[0]));
static int total_tests() {
    int n = 0;
    for (int i = 0; i < kGroupCount; ++i) n += kGroups[i].n;
    return n;
}

// Current selection.
static const Test *g_sel = &kBackends[3];  // Direct3D 11 preselected (matches mockup)
static const char *g_sel_group = "Graphics Backends";

// ===========================================================================
// Draw helpers.
// ===========================================================================
static void text_at(ImDrawList *dl, ImFont *f, float sz, ImVec2 p, ImU32 col, const char *s) {
    dl->AddText(f, sz, p, col, s);
}
static float text_w(ImFont *f, float sz, const char *s) {
    return f->CalcTextSizeA(sz, FLT_MAX, 0.0f, s).x;
}
// Uppercase, letter-spaced mono caps (group headers / telemetry keys). Returns width.
static float caps_at(ImDrawList *dl, ImFont *f, float sz, ImVec2 p, ImU32 col, const char *s,
                     float spacing) {
    float x = p.x;
    for (const char *c = s; *c; ++c) {
        char up = (*c >= 'a' && *c <= 'z') ? (char)(*c - 32) : *c;
        char b[2] = {up, 0};
        dl->AddText(f, sz, ImVec2(x, p.y), col, b);
        x += f->CalcTextSizeA(sz, FLT_MAX, 0.0f, b).x + spacing;
    }
    return x - p.x - spacing;
}
// Faux-bold: draw twice with a sub-pixel x offset.
static void bold_at(ImDrawList *dl, ImFont *f, float sz, ImVec2 p, ImU32 col, const char *s) {
    dl->AddText(f, sz, p, col, s);
    dl->AddText(f, sz, ImVec2(p.x + 0.6f, p.y), col, s);
}

// A small API chip: rounded square in the given hue.
static void chip(ImDrawList *dl, ImVec2 center, float half, ImU32 col, float glow = 0.0f) {
    if (glow > 0.0f) {
        dl->AddRectFilled(ImVec2(center.x - half - glow, center.y - half - glow),
                          ImVec2(center.x + half + glow, center.y + half + glow),
                          (col & 0x00ffffff) | 0x40000000, 3.0f);
    }
    dl->AddRectFilled(ImVec2(center.x - half, center.y - half),
                      ImVec2(center.x + half, center.y + half), col, 2.0f);
}

// Multi-color API glyph (mockup's conic gradient app icon), approximated as quadrants.
static void app_glyph(ImDrawList *dl, ImVec2 p, float sz) {
    float r = 5.0f;
    dl->AddRectFilled(p, ImVec2(p.x + sz, p.y + sz), H(0x1a2330), r);
    float m = sz * 0.5f;
    dl->AddRectFilled(ImVec2(p.x + 1, p.y + 1), ImVec2(p.x + m, p.y + m), g_hue[H_VK], 0);
    dl->AddRectFilled(ImVec2(p.x + m, p.y + 1), ImVec2(p.x + sz - 1, p.y + m), g_hue[H_DX9], 0);
    dl->AddRectFilled(ImVec2(p.x + 1, p.y + m), ImVec2(p.x + m, p.y + sz - 1), g_hue[H_GL], 0);
    dl->AddRectFilled(ImVec2(p.x + m, p.y + m), ImVec2(p.x + sz - 1, p.y + sz - 1), g_hue[H_DX12], 0);
    // inner cut-out
    float ir = sz * 0.22f;
    dl->AddRectFilled(ImVec2(p.x + m - ir, p.y + m - ir), ImVec2(p.x + m + ir, p.y + m + ir),
                      PAL.panel, 2.0f);
    dl->AddRect(p, ImVec2(p.x + sz, p.y + sz), IM_COL32(0, 0, 0, 64), r, 0, 1.0f);
}

static void heart(ImDrawList *dl, ImVec2 c, float s, ImU32 col) {
    dl->AddCircleFilled(ImVec2(c.x - s * 0.5f, c.y - s * 0.25f), s * 0.5f, col, 12);
    dl->AddCircleFilled(ImVec2(c.x + s * 0.5f, c.y - s * 0.25f), s * 0.5f, col, 12);
    dl->AddTriangleFilled(ImVec2(c.x - s * 0.95f, c.y - s * 0.02f),
                          ImVec2(c.x + s * 0.95f, c.y - s * 0.02f),
                          ImVec2(c.x, c.y + s * 0.9f), col);
}

// A styled button drawn on the current window's draw list via InvisibleButton.
// Returns true when clicked.
static bool chrome_button(const char *id, ImVec2 pos, ImVec2 size, const char *label, bool active) {
    ImDrawList *dl = ImGui::GetWindowDrawList();
    ImGui::SetCursorScreenPos(pos);
    ImGui::PushID(id);
    bool clicked = ImGui::InvisibleButton("b", size);
    bool hov = ImGui::IsItemHovered();
    ImGui::PopID();
    ImVec2 mx(pos.x + size.x, pos.y + size.y);
    ImU32 bg = active ? PAL.accent : (hov ? PAL.panelhi : PAL.panel);
    dl->AddRectFilled(pos, mx, bg, 8.0f);
    dl->AddRect(pos, mx, hov && !active ? PAL.accent : PAL.line2, 8.0f, 0, 1.0f);
    ImU32 tc = active ? H(0x04231f) : (hov ? PAL.text : PAL.muted);
    float tw = text_w(g_ui, 13.0f, label);
    text_at(dl, g_ui, 13.0f, ImVec2(pos.x + (size.x - tw) * 0.5f, pos.y + (size.y - 13.0f) * 0.5f),
            tc, label);
    return clicked;
}

// ===========================================================================
// Chrome regions.
// ===========================================================================
static int g_view_mode = 0;  // 0 = List, 1 = Grid

static void draw_titlebar(ImDrawList *dl, ImVec2 o, float w, float h) {
    dl->AddRectFilled(o, ImVec2(o.x + w, o.y + h), PAL.panelhi, 0);
    dl->AddLine(ImVec2(o.x, o.y + h - 0.5f), ImVec2(o.x + w, o.y + h - 0.5f), PAL.line, 1.0f);
    float cy = o.y + h * 0.5f;
    app_glyph(dl, ImVec2(o.x + 12.0f, cy - 9.0f), 18.0f);
    bold_at(dl, g_ui, 14.0f, ImVec2(o.x + 38.0f, cy - 7.5f), PAL.text, "AIO Graphics Test");
    float nx = o.x + 38.0f + text_w(g_ui, 14.0f, "AIO Graphics Test") + 10.0f;
    text_at(dl, g_mono, 11.0f, ImVec2(nx, cy - 6.0f), PAL.muted, AIO_VERSION);
    // decorative window controls
    float bx = o.x + w - 58.0f;
    dl->AddLine(ImVec2(bx, cy + 3), ImVec2(bx + 9, cy + 3), PAL.faint, 1.2f);
    dl->AddRect(ImVec2(bx + 20, cy - 4), ImVec2(bx + 29, cy + 4), PAL.faint, 1.5f, 0, 1.2f);
    dl->AddLine(ImVec2(bx + 40, cy - 4), ImVec2(bx + 49, cy + 4), PAL.faint, 1.2f);
    dl->AddLine(ImVec2(bx + 49, cy - 4), ImVec2(bx + 40, cy + 4), PAL.faint, 1.2f);
}

static void draw_toolbar(ImDrawList *dl, ImVec2 o, float w, float h) {
    dl->AddRectFilled(o, ImVec2(o.x + w, o.y + h), PAL.panel2, 0);
    dl->AddLine(ImVec2(o.x, o.y + h - 0.5f), ImVec2(o.x + w, o.y + h - 0.5f), PAL.line, 1.0f);
    float cy = o.y + h * 0.5f;
    // crumb: Group > Item
    float x = o.x + 14.0f;
    x += text_w(g_mono, 11.5f, g_sel_group);
    text_at(dl, g_mono, 11.5f, ImVec2(o.x + 14.0f, cy - 6.0f), PAL.muted, g_sel_group);
    text_at(dl, g_mono, 11.5f, ImVec2(x + 7.0f, cy - 6.0f), PAL.faint, ">");
    bold_at(dl, g_mono, 11.5f, ImVec2(x + 18.0f, cy - 6.0f), PAL.text, g_sel->name);

    // right cluster: [List | Grid] segmented + [Theme]
    float themeW = 84.0f, segW = 150.0f, segH = 28.0f, gap = 10.0f;
    float rx = o.x + w - 12.0f - themeW;
    // theme button
    char tlabel[24];
    snprintf(tlabel, sizeof(tlabel), "Theme  %s", g_dark ? "Dark" : "Light");
    if (chrome_button("##theme", ImVec2(rx, cy - segH * 0.5f), ImVec2(themeW, segH), tlabel, false))
        apply_theme(!g_dark);

    // segmented control container
    float sx = rx - gap - segW;
    ImVec2 sp(sx, cy - segH * 0.5f), smx(sx + segW, cy + segH * 0.5f);
    dl->AddRectFilled(sp, smx, PAL.panel, 8.0f);
    dl->AddRect(sp, smx, PAL.line2, 8.0f, 0, 1.0f);
    const char *segs[] = {"List", "Grid"};
    float innerW = (segW - 4.0f) / 2.0f;
    for (int i = 0; i < 2; ++i) {
        ImVec2 bp(sx + 2.0f + i * innerW, cy - segH * 0.5f + 2.0f);
        ImVec2 bmx(bp.x + innerW, cy + segH * 0.5f - 2.0f);
        ImGui::SetCursorScreenPos(bp);
        ImGui::PushID(i == 0 ? "##seglist" : "##seggrid");
        bool clk = ImGui::InvisibleButton("s", ImVec2(innerW, segH - 4.0f));
        bool hov = ImGui::IsItemHovered();
        ImGui::PopID();
        bool active = (g_view_mode == i);
        if (active) dl->AddRectFilled(bp, bmx, PAL.accent, 6.0f);
        ImU32 tc = active ? H(0x04231f) : (hov ? PAL.text : PAL.muted);
        // little glyph + label
        float lw = text_w(g_ui, 12.0f, segs[i]);
        float gly = 15.0f, tot = gly + 6.0f + lw;
        float gx = bp.x + (innerW - tot) * 0.5f, gcy = (bp.y + bmx.y) * 0.5f;
        if (i == 0) {  // list: three lines
            for (int k = 0; k < 3; ++k)
                dl->AddLine(ImVec2(gx, gcy - 4 + k * 4), ImVec2(gx + 12, gcy - 4 + k * 4), tc, 1.4f);
        } else {  // grid: four squares
            dl->AddRect(ImVec2(gx, gcy - 5), ImVec2(gx + 5, gcy), tc, 1.0f, 0, 1.3f);
            dl->AddRect(ImVec2(gx + 7, gcy - 5), ImVec2(gx + 12, gcy), tc, 1.0f, 0, 1.3f);
            dl->AddRect(ImVec2(gx, gcy + 2), ImVec2(gx + 5, gcy + 7), tc, 1.0f, 0, 1.3f);
            dl->AddRect(ImVec2(gx + 7, gcy + 2), ImVec2(gx + 12, gcy + 7), tc, 1.0f, 0, 1.3f);
        }
        text_at(dl, g_ui, 12.0f, ImVec2(gx + gly + 6.0f, gcy - 6.5f), tc, segs[i]);
        if (clk) g_view_mode = i;
    }
}

// Sparkline (draw-list, area-fill gradient + endpoint dot) using real frametimes.
static void draw_sparkline(ImDrawList *dl, ImVec2 p, ImVec2 size, const float *ring, int cap,
                           int offset) {
    const int N = 60;
    float vals[N];
    float mx = 2.0f;
    for (int i = 0; i < N; ++i) {
        int idx = (offset - N + i + cap * 4) % cap;
        vals[i] = ring[idx];
        if (vals[i] > mx) mx = vals[i];
    }
    mx *= 1.15f;
    dl->AddRectFilled(p, ImVec2(p.x + size.x, p.y + size.y), IM_COL32(6, 10, 14, 128), 6.0f);
    dl->AddRect(p, ImVec2(p.x + size.x, p.y + size.y), IM_COL32(255, 255, 255, 18), 6.0f, 0, 1.0f);
    // mid grid line
    dl->AddLine(ImVec2(p.x, p.y + size.y * 0.5f), ImVec2(p.x + size.x, p.y + size.y * 0.5f),
                IM_COL32(127, 240, 228, 30), 1.0f);
    float base = p.y + size.y;
    ImU32 top = IM_COL32(47, 214, 195, 102), bot = IM_COL32(47, 214, 195, 5);
    ImVec2 pts[N];
    for (int i = 0; i < N; ++i) {
        float x = p.x + (float)i / (N - 1) * size.x;
        float y = base - (vals[i] / mx) * size.y;
        pts[i] = ImVec2(x, y);
        if (i > 0)  // vertical gradient column under the curve
            dl->AddRectFilledMultiColor(ImVec2(pts[i - 1].x, pts[i - 1].y),
                                        ImVec2(x, base), top, top, bot, bot);
    }
    dl->AddPolyline(pts, N, IM_COL32(47, 214, 195, 255), 0, 1.6f);
    dl->AddCircleFilled(pts[N - 1], 2.4f, PAL.accentInk, 12);
}

static void draw_viewport(ImDrawList *dl, ImVec2 o, float w, float h, float fps,
                          const float *ring, int cap, int offset) {
    ImVec2 mx(o.x + w, o.y + h);
    dl->AddRectFilledMultiColor(o, mx, PAL.scr2, PAL.scr2, PAL.scr, PAL.scr);
    dl->AddLine(ImVec2(mx.x - 0.5f, o.y), ImVec2(mx.x - 0.5f, mx.y), PAL.line, 1.0f);

    if (g_sel->tool) {
        // Tool placeholder (GPU Info / Benchmark / Disk Speed report renders here in Phase 2).
        float tw = text_w(g_ui_big, 22.0f, g_sel->api);
        text_at(dl, g_ui_big, 22.0f, ImVec2(o.x + (w - tw) * 0.5f, o.y + h * 0.5f - 26.0f),
                PAL.scrText, g_sel->api);
        const char *sub = "report renders in this surface";
        float sw = caps_at(dl, g_mono_sm, 10.0f, ImVec2(o.x + w * 0.5f - 120.0f, o.y + h * 0.5f + 8.0f),
                           PAL.scrMuted, sub, 2.0f);
        (void)sw;
        return;
    }

    // ---- HUD (top-left) ----
    ImVec2 hp(o.x + 14.0f, o.y + 14.0f);
    // pill: chip + api + fps
    char fpsbuf[16];
    snprintf(fpsbuf, sizeof(fpsbuf), "%.0f", fps);
    float apiW = text_w(g_mono, 12.0f, g_sel->api);
    float fpsW = text_w(g_mono_bg, 20.0f, fpsbuf);
    float pillW = 12.0f + 14.0f + apiW + 12.0f + fpsW + 6.0f + text_w(g_mono_sm, 10.0f, "FPS") + 12.0f;
    float pillH = 34.0f;
    dl->AddRectFilled(hp, ImVec2(hp.x + pillW, hp.y + pillH), IM_COL32(6, 10, 14, 140), 9.0f);
    dl->AddRect(hp, ImVec2(hp.x + pillW, hp.y + pillH), IM_COL32(255, 255, 255, 20), 9.0f, 0, 1.0f);
    float hcy = hp.y + pillH * 0.5f;
    chip(dl, ImVec2(hp.x + 14.0f, hcy), 4.0f, hue_col(g_sel->hue), 3.0f);
    bold_at(dl, g_mono, 12.0f, ImVec2(hp.x + 24.0f, hcy - 6.0f), IM_COL32(255, 255, 255, 255),
            g_sel->api);
    float fx = hp.x + 24.0f + apiW + 12.0f;
    bold_at(dl, g_mono_bg, 20.0f, ImVec2(fx, hcy - 11.0f), PAL.accentInk, fpsbuf);
    text_at(dl, g_mono_sm, 10.0f, ImVec2(fx + fpsW + 4.0f, hcy - 1.0f), PAL.scrMuted, "FPS");

    // frametime label + sparkline + ms line
    ImVec2 slp(o.x + 14.0f, hp.y + pillH + 10.0f);
    caps_at(dl, g_mono_sm, 9.5f, slp, PAL.scrMuted, "Frametime", 2.0f);
    ImVec2 spk(o.x + 14.0f, slp.y + 15.0f);
    draw_sparkline(dl, spk, ImVec2(200.0f, 34.0f), ring, cap, offset);
    // ms / avg / 1% from the ring buffer
    float sum = 0.0f, worst = 0.0f;
    for (int i = 0; i < cap; ++i) { sum += ring[i]; if (ring[i] > worst) worst = ring[i]; }
    float avg = sum / cap, cur = fps > 0 ? 1000.0f / fps : 0.0f;
    char msbuf[80];
    snprintf(msbuf, sizeof(msbuf), "%.2f ms   avg %.2f   1%% %.2f", cur, avg, worst);
    text_at(dl, g_mono_sm, 11.0f, ImVec2(spk.x + 2.0f, spk.y + 40.0f), PAL.scrMuted, msbuf);

    // ---- telemetry strip (bottom) ----
    float stripH = 58.0f, sy = mx.y - stripH;
    dl->AddRectFilledMultiColor(ImVec2(o.x, sy), mx, IM_COL32(4, 7, 10, 0), IM_COL32(4, 7, 10, 0),
                                IM_COL32(4, 7, 10, 210), IM_COL32(4, 7, 10, 210));
    struct Cell { const char *k; const char *v; bool path; };
    char resbuf[] = "1280 x 720";
    Cell cells[] = {
        {"Resolution", resbuf, false},
        {"Present", g_sel->present ? g_sel->present : "FIFO (vsync off)", false},
        {"Translation path", g_sel->path ? g_sel->path : "-", true},
        {"GPU", "Adreno 750", false},
    };
    float cx = o.x + 14.0f, cellY = mx.y - 34.0f;
    for (int i = 0; i < 4; ++i) {
        caps_at(dl, g_mono_sm, 9.0f, ImVec2(cx, cellY), PAL.scrMuted, cells[i].k, 1.5f);
        ImU32 vc = cells[i].path ? PAL.accentInk : PAL.scrText;
        text_at(dl, g_mono, 12.0f, ImVec2(cx, cellY + 13.0f), vc, cells[i].v);
        float kw = caps_at(dl, g_mono_sm, 9.0f, ImVec2(-9999, -9999), PAL.scrMuted, cells[i].k, 1.5f);
        float vw = text_w(g_mono, 12.0f, cells[i].v);
        float cw = (kw > vw ? kw : vw);
        cx += cw + 22.0f;
        if (i < 3) {
            dl->AddLine(ImVec2(cx - 11.0f, cellY - 2.0f), ImVec2(cx - 11.0f, cellY + 27.0f),
                        IM_COL32(255, 255, 255, 16), 1.0f);
        }
    }
}

// One menu list row.
static void menu_row(const Test *t, const char *group, float w) {
    const float ROWH = 30.0f;
    ImDrawList *dl = ImGui::GetWindowDrawList();
    ImVec2 p = ImGui::GetCursorScreenPos();
    ImGui::PushID((void *)t);
    bool clicked = ImGui::InvisibleButton("row", ImVec2(w, ROWH));
    bool hov = ImGui::IsItemHovered();
    ImGui::PopID();
    bool sel = (t == g_sel);
    ImVec2 mx(p.x + w, p.y + ROWH);
    if (sel) {
        dl->AddRectFilled(p, mx, PAL.panelhi, 7.0f);
        dl->AddRectFilled(p, ImVec2(p.x + 2.0f, mx.y), PAL.accent, 0);
    } else if (hov) {
        dl->AddRectFilled(p, mx, PAL.panel2, 7.0f);
    }
    float cy = p.y + ROWH * 0.5f;
    chip(dl, ImVec2(p.x + 13.0f, cy), 4.5f, hue_col(t->hue));
    ImVec2 np(p.x + 27.0f, cy - 7.0f);
    if (sel) bold_at(dl, g_ui, 13.0f, np, PAL.text, t->name);
    else text_at(dl, g_ui, 13.0f, np, PAL.text, t->name);
    if (t->fps) {
        char fb[16];
        snprintf(fb, sizeof(fb), "%d fps", t->fps);
        float fw = text_w(g_mono, 10.5f, fb);
        text_at(dl, g_mono, 10.5f, ImVec2(mx.x - fw - 10.0f, cy - 5.5f), PAL.muted, fb);
    }
    if (clicked) { g_sel = t; g_sel_group = group; }
}

// One menu grid tile.
static void menu_tile(const Test *t, const char *group, float x, float y, float w, float hh) {
    const float CARDH = hh;
    ImDrawList *dl = ImGui::GetWindowDrawList();
    ImGui::SetCursorScreenPos(ImVec2(x, y));
    ImGui::PushID((void *)t);
    bool clicked = ImGui::InvisibleButton("tile", ImVec2(w, CARDH));
    bool hov = ImGui::IsItemHovered();
    ImGui::PopID();
    bool sel = (t == g_sel);
    ImVec2 p(x, y), mx(x + w, y + CARDH);
    dl->AddRectFilled(p, mx, hov ? PAL.panelhi : PAL.panel2, 10.0f);
    if (sel) {
        dl->AddRect(p, mx, PAL.accent, 10.0f, 0, 1.5f);
        dl->AddRect(ImVec2(p.x - 1, p.y - 1), ImVec2(mx.x + 1, mx.y + 1),
                    (PAL.accent & 0x00ffffff) | 0x33000000, 11.0f, 0, 2.0f);
    } else {
        dl->AddRect(p, mx, PAL.line, 10.0f, 0, 1.0f);
    }
    dl->AddRectFilled(p, ImVec2(p.x + 3.0f, mx.y), hue_col(t->hue), 10.0f, ImDrawFlags_RoundCornersLeft);
    if (sel) bold_at(dl, g_ui, 12.5f, ImVec2(p.x + 12.0f, p.y + 10.0f), PAL.text, t->name);
    else text_at(dl, g_ui, 12.5f, ImVec2(p.x + 12.0f, p.y + 10.0f), PAL.text, t->name);
    char sub[24];
    if (t->fps) snprintf(sub, sizeof(sub), "%d fps", t->fps);
    else snprintf(sub, sizeof(sub), "%s", t->api);
    text_at(dl, g_mono, 10.0f, ImVec2(p.x + 12.0f, p.y + CARDH - 18.0f), PAL.muted, sub);
    if (clicked) { g_sel = t; g_sel_group = group; }
}

static void draw_menu(ImDrawList *dl, ImVec2 o, float w, float h) {
    ImVec2 mx(o.x + w, o.y + h);
    dl->AddRectFilled(o, mx, PAL.panel, 0);
    // header
    float headH = 52.0f;
    bold_at(dl, g_ui, 13.0f, ImVec2(o.x + 15.0f, o.y + 12.0f), PAL.text, "Tests");
    char sub[64];
    snprintf(sub, sizeof(sub), "%d tests  -  %s", total_tests(),
             g_view_mode == 0 ? "grouped list" : "tile grid");
    text_at(dl, g_mono, 11.0f, ImVec2(o.x + 15.0f, o.y + 30.0f), PAL.muted, sub);
    dl->AddLine(ImVec2(o.x, o.y + headH - 0.5f), ImVec2(mx.x, o.y + headH - 0.5f), PAL.line, 1.0f);

    // scroll region
    ImGui::SetCursorScreenPos(ImVec2(o.x, o.y + headH));
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(10.0f, 8.0f));
    ImGui::BeginChild("##menuscroll", ImVec2(w, h - headH), false,
                      ImGuiWindowFlags_NoBackground);
    ImDrawList *cdl = ImGui::GetWindowDrawList();
    float avail = ImGui::GetContentRegionAvail().x;
    for (int g = 0; g < kGroupCount; ++g) {
        const Group &grp = kGroups[g];
        // group header: caps + divider line
        ImGui::Dummy(ImVec2(0, g == 0 ? 2.0f : 10.0f));
        ImVec2 hp = ImGui::GetCursorScreenPos();
        float hw = caps_at(cdl, g_mono_sm, 9.5f, ImVec2(hp.x + 6.0f, hp.y + 4.0f), PAL.faint,
                           grp.name, 1.8f);
        cdl->AddLine(ImVec2(hp.x + 6.0f + hw + 8.0f, hp.y + 8.0f),
                     ImVec2(hp.x + avail - 4.0f, hp.y + 8.0f), PAL.line, 1.0f);
        ImGui::Dummy(ImVec2(avail, 20.0f));

        if (g_view_mode == 0) {
            for (int i = 0; i < grp.n; ++i) menu_row(&grp.items[i], grp.name, avail);
        } else {
            float gap = 8.0f, cw = (avail - gap - 12.0f) / 2.0f, ch = 50.0f;
            float x0 = ImGui::GetCursorScreenPos().x + 6.0f;
            for (int i = 0; i < grp.n; i += 2) {
                float y = ImGui::GetCursorScreenPos().y;
                menu_tile(&grp.items[i], grp.name, x0, y, cw, ch);
                if (i + 1 < grp.n)
                    menu_tile(&grp.items[i + 1], grp.name, x0 + cw + gap, y, cw, ch);
                ImGui::SetCursorScreenPos(ImVec2(ImGui::GetCursorScreenPos().x, y));
                ImGui::Dummy(ImVec2(avail, ch + gap));
            }
        }
    }
    ImGui::Dummy(ImVec2(0, 8.0f));
    ImGui::EndChild();
    ImGui::PopStyleVar();
}

static void draw_footer(ImDrawList *dl, ImVec2 o, float w, float h) {
    dl->AddRectFilled(o, ImVec2(o.x + w, o.y + h), PAL.panel2, 0);
    dl->AddLine(ImVec2(o.x, o.y + 0.5f), ImVec2(o.x + w, o.y + 0.5f), PAL.line, 1.0f);
    float cy = o.y + h * 0.5f;
    float x = o.x + 14.0f;
    text_at(dl, g_ui, 11.5f, ImVec2(x, cy - 6.5f), PAL.muted, "Built with");
    x += text_w(g_ui, 11.5f, "Built with") + 7.0f;
    heart(dl, ImVec2(x + 5.0f, cy), 4.5f, PAL.bad);
    x += 14.0f;
    text_at(dl, g_ui, 11.5f, ImVec2(x, cy - 6.5f), PAL.muted, "for the Emulation Community");
    char rbuf[48];
    snprintf(rbuf, sizeof(rbuf), "AIO Graphics Test  %s", AIO_VERSION);
    float rw = text_w(g_mono, 11.0f, rbuf);
    text_at(dl, g_mono, 11.0f, ImVec2(o.x + w - rw - 14.0f, cy - 6.0f), PAL.muted, rbuf);
}

// ===========================================================================
// Entry point.
// ===========================================================================
extern "C" int aio_run_imgui_shell(HINSTANCE hInstance) {
    WNDCLASSEXA wc;
    ZeroMemory(&wc, sizeof(wc));
    wc.cbSize = sizeof(wc);
    wc.style = CS_HREDRAW | CS_VREDRAW;
    wc.lpfnWndProc = wnd_proc;
    wc.hInstance = hInstance;
    wc.hCursor = LoadCursor(nullptr, IDC_ARROW);
    wc.lpszClassName = "AIOImGuiShell";
    RegisterClassExA(&wc);

    HWND hwnd = CreateWindowA(wc.lpszClassName, "AIO Graphics Test", WS_OVERLAPPEDWINDOW, 100, 100,
                              1180, 720, nullptr, nullptr, hInstance, nullptr);
    if (!hwnd) {
        UnregisterClassA(wc.lpszClassName, hInstance);
        return 1;
    }

    if (!create_device(hwnd)) {
        destroy_device();
        DestroyWindow(hwnd);
        UnregisterClassA(wc.lpszClassName, hInstance);
        MessageBoxA(nullptr,
                    "Direct3D 11 is not available in this container.\n\n"
                    "Could not create a D3D11 device + swapchain (no d3d11.dll / DXVK?).\n"
                    "The ImGui shell requires the container's DXVK DLL set.",
                    "AIO Graphics Test", MB_OK | MB_ICONERROR);
        return 1;
    }

    ShowWindow(hwnd, SW_SHOWDEFAULT);
    UpdateWindow(hwnd);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO &io = ImGui::GetIO();
    io.IniFilename = nullptr;  // do not persist layout

    // Embedded fonts.
    ImFontConfig cfg;
    cfg.OversampleH = 3; cfg.OversampleV = 2; cfg.PixelSnapH = false;
    g_ui = io.Fonts->AddFontFromMemoryCompressedBase85TTF(InterUI_compressed_data_base85, 14.0f, &cfg);
    g_ui_big = io.Fonts->AddFontFromMemoryCompressedBase85TTF(InterUI_compressed_data_base85, 19.0f, &cfg);
    g_mono = io.Fonts->AddFontFromMemoryCompressedBase85TTF(CascadiaMono_compressed_data_base85, 12.0f, &cfg);
    g_mono_sm = io.Fonts->AddFontFromMemoryCompressedBase85TTF(CascadiaMono_compressed_data_base85, 10.0f, &cfg);
    g_mono_bg = io.Fonts->AddFontFromMemoryCompressedBase85TTF(CascadiaMono_compressed_data_base85, 20.0f, &cfg);
    io.FontDefault = g_ui;

    init_hues();
    apply_theme(true);  // dark default
    ImGui_ImplWin32_Init(hwnd);
    ImGui_ImplDX11_Init(g_dev, g_ctx);

    // Real frametime ring buffer.
    static float frametimes[120];
    for (int i = 0; i < 120; ++i) frametimes[i] = 16.6f;
    int ft_offset = 0;
    LARGE_INTEGER freq, prev;
    QueryPerformanceFrequency(&freq);
    QueryPerformanceCounter(&prev);
    float fps_smooth = 0.0f;

    bool done = false;
    while (!done) {
        MSG msg;
        while (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE)) {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
            if (msg.message == WM_QUIT) done = true;
        }
        if (done) break;

        LARGE_INTEGER now;
        QueryPerformanceCounter(&now);
        double dt_ms = (double)(now.QuadPart - prev.QuadPart) * 1000.0 / (double)freq.QuadPart;
        prev = now;
        if (dt_ms < 0.0) dt_ms = 0.0;
        frametimes[ft_offset] = (float)dt_ms;
        ft_offset = (ft_offset + 1) % 120;
        float inst_fps = dt_ms > 0.0 ? (float)(1000.0 / dt_ms) : 0.0f;
        fps_smooth = fps_smooth <= 0.0f ? inst_fps : fps_smooth * 0.9f + inst_fps * 0.1f;

        ImGui_ImplDX11_NewFrame();
        ImGui_ImplWin32_NewFrame();
        ImGui::NewFrame();

        ImGuiViewport *vp = ImGui::GetMainViewport();
        ImVec2 o = vp->WorkPos;
        float W = vp->WorkSize.x, Hh = vp->WorkSize.y;
        ImGui::SetNextWindowPos(o);
        ImGui::SetNextWindowSize(ImVec2(W, Hh));
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
        ImGuiWindowFlags rflags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
                                  ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollbar |
                                  ImGuiWindowFlags_NoScrollWithMouse | ImGuiWindowFlags_NoCollapse |
                                  ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoBringToFrontOnFocus |
                                  ImGuiWindowFlags_NoNavFocus;
        ImGui::Begin("##root", nullptr, rflags);
        ImDrawList *dl = ImGui::GetWindowDrawList();

        const float TITLE_H = 34.0f, TOOL_H = 40.0f, FOOT_H = 34.0f, PANEL_W = 320.0f;
        float bodyTop = o.y + TITLE_H + TOOL_H;
        float bodyH = Hh - TITLE_H - TOOL_H - FOOT_H;
        float vpW = W - PANEL_W;

        dl->AddRectFilled(o, ImVec2(o.x + W, o.y + Hh), PAL.bg, 0);
        draw_titlebar(dl, o, W, TITLE_H);
        draw_toolbar(dl, ImVec2(o.x, o.y + TITLE_H), W, TOOL_H);
        draw_viewport(dl, ImVec2(o.x, bodyTop), vpW, bodyH, fps_smooth, frametimes, 120, ft_offset);
        draw_menu(dl, ImVec2(o.x + vpW, bodyTop), PANEL_W, bodyH);
        draw_footer(dl, ImVec2(o.x, o.y + Hh - FOOT_H), W, FOOT_H);

        ImGui::End();
        ImGui::PopStyleVar();

        ImGui::Render();
        const float clear[4] = {0.027f, 0.039f, 0.055f, 1.0f};
        g_ctx->OMSetRenderTargets(1, &g_rtv, nullptr);
        g_ctx->ClearRenderTargetView(g_rtv, clear);
        ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
        g_swap->Present(1, 0);
    }

    ImGui_ImplDX11_Shutdown();
    ImGui_ImplWin32_Shutdown();
    ImGui::DestroyContext();
    destroy_device();
    DestroyWindow(hwnd);
    UnregisterClassA(wc.lpszClassName, hInstance);
    return 0;
}
